Repository catalanomircosav/QT, pull requests merged in 2025-05, with the labels that each got.

#35 Qt2 completato.
  README.md
  assets/uml_qt2.png
Labels: documentation

#45 Risolte duplicazioni dei file
  ArraySet.java
  Attribute.java
  Cluster.java
  ClusterSet.java
  ContinuousAttribute.java
  Data.java
  DiscreteAttribute.java
  DiscreteItem.java
  Item.java
  Keyboard.java
  QTMiner.java
  Tuple.java
Labels: bug

#48 QT3
  .gitignore
  README.md
  UML.md
  assets/uml_qt3.png
  data/Tuple.java
Labels: documentation

#62 Modificata la classe Data secondo le specifiche richieste.
  data/Data.java
Labels: enhancement

#64 Modificata la funzione avgDistance
  data/Data.java
  data/Tuple.java
  mining/Cluster.java
Labels: enhancement

#63 Sistemato DiscreteAttribute e sistemato problema nel main
  MainTest.java
  data/DiscreteAttribute.java
Labels: enhancement

#65 Rimozione classe ArraySet e implementazione HashSet
  data/Tuple.java
  mining/Cluster.java
  utility/ArraySet.java
Labels: enhancement

#66 Modifiche a Cluster e di consguenza QTMiner + minor fix
  data/DiscreteAttribute.java
  mining/Cluster.java
  mining/QTMiner.java
Labels: enhancement

#67 Riorganizzazione del ClusterSet
  mining/ClusterSet.java
Labels: enhancement

#68 Aggiunta ContinuousItem
  data/ContinuousItem.java
Labels: code

#70 Aggiornato tutto con Generics
  data/ContinuousItem.java
  data/DiscreteItem.java
  data/Item.java
  data/Tuple.java
Labels: enhancement
